config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post 'welcome/plot'

end

app/models/capital.rb
class Capital
  include Mongoid::Document
  field :city, type: String
  field :state, type: String
  field :loc, type: Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
require 'citymod'
require 'ga'
require 'populationmod'
require 'tour_manager'
require 'tourmod'

class WelcomeController < ApplicationController
  include Citymod
  include GA
  include Populationmod
  include TourManager
  include Tourmod
  
  def index
    @capitals = Capital.all

  end
  
  def plot
    @cities = []
    params.each do |param|
      if param[0] =~ /^city/
        @cities << param[1]
      end
    end
    
    @cities.each do |city_name|
      city_data = Capital.where(city: city_name).first
      new_city = City.new(city_data.loc[0], city_data.loc[1], "#{city_data.city}, #{city_data.state}");
      TourManager.add_city(new_city);
    end
 
      
    population = Population.new(100, true) 
    
    # Evolve population
    population = GA.evolve_population( population )
    population = GA.evolve_population( population )
    100.times do
      population = GA.evolve_population( population )
    end

    @solution = population.fittest.to_s
    
    #
    # puts "Finished"
    # puts "Final distance: #{population.fittest.distance}"
    # puts "Solution:"
    # puts population.fittest.to_s
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tsp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.slim
div class='container'

  h1 US Capitals

  = form_tag(welcome_plot_path, method: "post") do
    - @capitals.each_with_index do |capital, i|
      div class='checkbox'
	    - box_name = "city#{i}"
	    = check_box_tag(box_name, capital.city) 
        | #{capital.city}, #{capital.state}
	
	div class='submit'
	  = submit_tag("Plot")

app/views/welcome/plot.html.slim
div class='container'

  h1 Cities
  
  ul
    - @cities.each do |city|
	  li #{city}
	  
  h3 Solution:
  
  p #{@solution}